apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: MINIKUBE_IP
  selector:
    app: grafana
  ports:
  - port: 3000
    name: grafana
---
