apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
    #replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Never
        name: nginx
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
      metallb.universe.tf/allow-shared-ip: "shared"
spec:
  type: LoadBalancer
  loadBalancerIP: MINIKUBE_IP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
      #    - name: ssh
      #port: 22
      #protocol: TCP
      #targetPort: 22


